from enum import Enum


class Half(str, Enum):
    FIRST = "FIRST"
    SECOND = "SECOND"
    # v1 scope: EXTRA_TIME and PENALTIES intentionally excluded.
    # Add in a future version when cup/knockout match support is required.


class CVEntityType(str, Enum):
    PLAYER = "PLAYER"
    REFEREE = "REFEREE"
    BALL = "BALL"


class PlayerRole(str, Enum):
    GK = "GK"
    OUTFIELD = "OUTFIELD"


class EventType(str, Enum):
    # Positional
    PLAYER_POSITION = "PLAYER_POSITION"
    BALL_POSITION = "BALL_POSITION"
    # Ball events
    PASS = "PASS"
    SHOT = "SHOT"
    DRIBBLE = "DRIBBLE"
    CLEARANCE = "CLEARANCE"
    INTERCEPTION = "INTERCEPTION"
    TACKLE = "TACKLE"
    # Spatial
    PRESSURE = "PRESSURE"
    CARRY = "CARRY"
    OFFSIDE_LINE = "OFFSIDE_LINE"
    PRESSURE_ZONE = "PRESSURE_ZONE"
    # Match lifecycle
    MATCH_START = "MATCH_START"
    MATCH_END = "MATCH_END"
    HALF_START = "HALF_START"
    HALF_END = "HALF_END"
    SUBSTITUTION = "SUBSTITUTION"
    FORMATION_CHANGE = "FORMATION_CHANGE"
    # System
    SOURCE_CONNECTED = "SOURCE_CONNECTED"
    SOURCE_DISCONNECTED = "SOURCE_DISCONNECTED"
    REPLAY_COMPLETE = "REPLAY_COMPLETE"


class FeatureType(str, Enum):
    FRAME_WISE = "FRAME_WISE"
    MATCH_STATE = "MATCH_STATE"


class FeatureCategory(str, Enum):
    INDIVIDUAL = "INDIVIDUAL"
    TEAM = "TEAM"
    MATCH = "MATCH"


class UpdateTrigger(str, Enum):
    CONTINUOUS = "CONTINUOUS"
    EVENT_DRIVEN = "EVENT_DRIVEN"


class EntityType(str, Enum):
    PLAYER = "PLAYER"
    TEAM = "TEAM"


class AnomalyType(str, Enum):
    PRESSING_TRIGGER = "PRESSING_TRIGGER"
    COUNTER_ATTACK_LAUNCH = "COUNTER_ATTACK_LAUNCH"
    OVERLOAD_ZONE = "OVERLOAD_ZONE"
    DEFENSIVE_LINE_BREAK = "DEFENSIVE_LINE_BREAK"
    SHAPE_DISRUPTION = "SHAPE_DISRUPTION"
    FATIGUE_SIGNATURE = "FATIGUE_SIGNATURE"
    HIGH_DANGER_BUILDUP = "HIGH_DANGER_BUILDUP"
    DEAD_BALL_OPPORTUNITY = "DEAD_BALL_OPPORTUNITY"


class ScoreType(str, Enum):
    THREAT_PROBABILITY = "THREAT_PROBABILITY"
    PRESS_SUCCESS_PROBABILITY = "PRESS_SUCCESS_PROBABILITY"
    THROUGH_BALL_VIABILITY = "THROUGH_BALL_VIABILITY"
    TACTICAL_STABILITY = "TACTICAL_STABILITY"
    TRANSITION_EXPOSURE = "TRANSITION_EXPOSURE"
    SET_PIECE_THREAT = "SET_PIECE_THREAT"
    FATIGUE_INDEX = "FATIGUE_INDEX"
    OPPONENT_PREDICTABILITY = "OPPONENT_PREDICTABILITY"


class CallType(str, Enum):
    SUBSTITUTION = "SUBSTITUTION"
    SHAPE_CHANGE = "SHAPE_CHANGE"
    PRESSING_INSTRUCTION = "PRESSING_INSTRUCTION"
    DROP_BLOCK = "DROP_BLOCK"
    WIDTH_ADJUSTMENT = "WIDTH_ADJUSTMENT"
    DEFENSIVE_LINE_HEIGHT = "DEFENSIVE_LINE_HEIGHT"
    EXPLOIT_FLAG = "EXPLOIT_FLAG"
    VULNERABILITY_FLAG = "VULNERABILITY_FLAG"


class Urgency(str, Enum):
    IMMEDIATE = "IMMEDIATE"
    NEXT_DEAD_BALL = "NEXT_DEAD_BALL"
    ADVISORY = "ADVISORY"


class LicenseTier(str, Enum):
    BASIC = "BASIC"
    PRO = "PRO"
    ENTERPRISE = "ENTERPRISE"


class LicenseStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    EXPIRED = "EXPIRED"
    TRIAL = "TRIAL"


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    HEAD_COACH = "HEAD_COACH"
    ASSISTANT_COACH = "ASSISTANT_COACH"
    ANALYST = "ANALYST"
    VIDEO_OPERATOR = "VIDEO_OPERATOR"
